```{r, include = FALSE, message = FALSE, warning = FALSE}
library(exams)
```

```{r data_generation, echo = FALSE, results = "hide"}
#Dados da questao

#Faca a resposta correta ser a primeira e as outras falsas
questions <- paste(c("$E(\\hat{\\theta}) = \\theta$.", "$\\hat{\\theta} = \\theta$.", "a variância de $\\hat{\\theta}$ é igual a variância de $\\theta$.", "$\\hat{\\theta} = \\theta$, apenas quando a amostra tiver mais do que 30 observações.", "$\\hat{\\theta}$ terá sempre distribuição normal."))
solutions <- c(TRUE, rep(FALSE, 4))

o <- sample(1:5)
questions <- questions[o]
solutions <- solutions[o]
```

Question
========
Sabe-se que $\hat{\theta}$ é um estimador não tendencioso do parâmetro populacional $\theta$. Assim,

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========
$E(\hat{\theta}) = \theta$ porque o estimador de um parâmetro é tal que sua esperança matemática seja igual ao valor verdadeiro desse parâmetro.


```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "Correta", "Incorreta"), markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions, single = TRUE)`
exname: prop. estimadores
